overrides:
  got@<11.8.5: ">=11.8.5"
  postcss@<8.4.31: ">=8.4.31"
  sharp@<0.32.6: ">=0.32.6"
  webpack-dev-middleware@<=5.3.3: ">=5.3.4"
  axios@>=0.8.1 <0.28.0: ">=0.28.0"
  ws@>=8.0.0 <8.17.1: ">=8.17.1"
  socket.io@>=3.0.0 <4.6.2: ">=4.6.2"
  semver@>=7.0.0 <7.5.2: ">=7.5.2"
  engine.io@>=5.1.0 <6.4.2: ">=6.4.2"
  axios@<0.30.0: ">=0.30.0"
  cookie@<0.7.0: ">=0.7.0"
